#!/bin/bash
# 准备上传到GitHub的脚本

echo "=========================================="
echo "ResFoD - GitHub 上传准备"
echo "=========================================="
echo ""

# 检查git状态
echo "📋 检查Git状态..."
git status --short

echo ""
echo "=========================================="
echo "✅ 已准备的文件："
echo "=========================================="
echo "核心代码："
echo "  - models/          (模型架构)"
echo "  - utils/           (工具函数)"
echo ""
echo "文档："
echo "  - README.md        (项目说明)"
echo "  - METHODOLOGY.md   (技术文档)"
echo "  - CONTRIBUTING.md  (贡献指南)"
echo "  - requirements.txt (依赖包)"
echo ""
echo "配置："
echo "  - .gitignore       (Git忽略规则)"
echo ""
echo "=========================================="
echo "❌ 已排除的文件（不会上传）："
echo "=========================================="
echo "  - results/                    (训练结果)"
echo "  - train_IR.py                 (训练脚本)"
echo "  - inference.py                (推理脚本)"
echo "  - train*.sh                   (训练脚本)"
echo "  - run_inference.sh            (推理脚本)"
echo "  - convert_allweather_to_lmdb.py (数据转换)"
echo ""
echo "=========================================="
echo "📝 下一步操作："
echo "=========================================="
echo "1. 提交代码到本地仓库："
echo "   git commit -m 'Initial commit: Add core ResFoD implementation'"
echo ""
echo "2. 在GitHub创建新仓库"
echo ""
echo "3. 连接并推送："
echo "   git remote add origin https://github.com/YOUR_USERNAME/resfod.git"
echo "   git push -u origin master"
echo ""
echo "详细步骤请查看 GITHUB_SETUP.md"
echo ""
